[2023-12-20T23:07:57.949+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_dag.print_hello scheduled__2020-10-14T00:00:00+00:00 [queued]>
[2023-12-20T23:08:32.541+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_dag.print_hello scheduled__2020-10-14T00:00:00+00:00 [queued]>
[2023-12-20T23:08:32.956+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2023-12-20T23:08:38.115+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): print_hello> on 2020-10-14 00:00:00+00:00
[2023-12-20T23:08:38.222+0000] {standard_task_runner.py:60} INFO - Started process 611 to run task
[2023-12-20T23:08:39.159+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'bash_dag', 'print_hello', 'scheduled__2020-10-14T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/util_dag_bash/bash_dag.py', '--cfg-path', '/tmp/tmpm0wk2_dy']
[2023-12-20T23:08:44.023+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask print_hello
[2023-12-20T23:09:08.476+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-12-20T23:09:11.657+0000] {process_utils.py:131} INFO - Sending 15 to group 611. PIDs of all processes in the group: [611]
[2023-12-20T23:09:12.081+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 611
[2023-12-20T23:09:25.686+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=611, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='23:08:37') (611) terminated with exit code -15
