[2023-12-20T23:04:23.497+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_dag.print_hello scheduled__2020-10-03T00:00:00+00:00 [queued]>
[2023-12-20T23:04:36.714+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_dag.print_hello scheduled__2020-10-03T00:00:00+00:00 [queued]>
[2023-12-20T23:04:37.484+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2023-12-20T23:11:04.177+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): print_hello> on 2020-10-03 00:00:00+00:00
[2023-12-20T23:11:06.496+0000] {standard_task_runner.py:60} INFO - Started process 655 to run task
[2023-12-20T23:11:08.583+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'bash_dag', 'print_hello', 'scheduled__2020-10-03T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/util_dag_bash/bash_dag.py', '--cfg-path', '/tmp/tmpyofnl52v']
[2023-12-20T23:11:10.082+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask print_hello
[2023-12-20T23:11:26.127+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-12-20T23:11:27.985+0000] {process_utils.py:131} INFO - Sending 15 to group 655. PIDs of all processes in the group: [655]
[2023-12-20T23:11:28.364+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 655
[2023-12-20T23:11:34.173+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=655, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='23:11:06') (655) terminated with exit code -15
